// Wordle 5-letter word list
export const WORDLE_WORDS = [
  // Common words
  'about', 'above', 'abuse', 'admit', 'adopt', 'adult', 'after', 'again', 'agent', 'agree',
  'ahead', 'album', 'alert', 'align', 'alike', 'alive', 'allow', 'alone', 'along', 'alter',
  'angel', 'anger', 'angle', 'angry', 'apart', 'apple', 'apply', 'arena', 'argue', 'arise',
  'array', 'arrow', 'aside', 'asset', 'avoid', 'awake', 'award', 'aware', 'badly', 'baker',
  'bases', 'basic', 'basis', 'beach', 'began', 'begin', 'being', 'below', 'bench', 'billy',
  'birth', 'black', 'blade', 'blame', 'blank', 'blast', 'bleed', 'blend', 'bless', 'blind',
  'block', 'blood', 'bloom', 'blown', 'board', 'boost', 'booth', 'bound', 'brain', 'brand',
  'brass', 'brave', 'bread', 'break', 'breed', 'brian', 'brick', 'bride', 'brief', 'bring',
  'brink', 'broad', 'broke', 'brook', 'brown', 'build', 'built', 'buyer', 'cable', 'calif',
  'camel', 'canal', 'candy', 'canon', 'carry', 'carve', 'catch', 'cause', 'chain', 'chair',
  'chaos', 'charm', 'chart', 'chase', 'cheap', 'cheat', 'check', 'cheek', 'cheer', 'chess',
  'chest', 'chief', 'child', 'china', 'chose', 'civic', 'civil', 'claim', 'class', 'clean',
  'clear', 'click', 'cliff', 'climb', 'clock', 'close', 'cloth', 'cloud', 'coach', 'coast',
  'cobra', 'colon', 'color', 'comet', 'comic', 'coral', 'couch', 'count', 'court', 'cover',
  'crack', 'craft', 'crash', 'crate', 'crazy', 'cream', 'creep', 'crime', 'cross', 'crowd',
  'crown', 'crude', 'crush', 'curve', 'cycle', 'daddy', 'daily', 'dance', 'dated', 'dealt',
  'death', 'debut', 'decay', 'decor', 'decoy', 'defer', 'deity', 'delay', 'delta', 'dense',
  'depth', 'derby', 'deter', 'devon', 'diary', 'dirty', 'disco', 'dived', 'diver', 'dodge',
  'doing', 'dolly', 'donna', 'donor', 'doubt', 'dough', 'dover', 'draft', 'drain', 'drake',
  'drama', 'drank', 'drawn', 'dread', 'dream', 'dress', 'dried', 'drier', 'drift', 'drill',
  'drink', 'drive', 'droit', 'drone', 'drove', 'drown', 'drugs', 'drunk', 'dryly', 'dutch',
  'duvet', 'dwarf', 'dwell', 'dying', 'eager', 'eagle', 'early', 'earth', 'easel', 'easly',
  'eaten', 'eater', 'ebony', 'eight', 'eject', 'elbow', 'elder', 'elect', 'elite', 'email',
  'ember', 'emery', 'empty', 'enemy', 'enjoy', 'enter', 'entry', 'envoy', 'equal', 'equip',
  'erase', 'erect', 'erode', 'error', 'erupt', 'essay', 'ether', 'ethic', 'evade', 'event',
  'every', 'evoke', 'exact', 'exams', 'excel', 'exile', 'exist', 'expat', 'extra', 'exude',
  'fable', 'faced', 'facet', 'facts', 'faded', 'faint', 'fairy', 'faith', 'false', 'famed',
  'fancy', 'farce', 'fatal', 'fault', 'fauna', 'favor', 'feast', 'feats', 'fence', 'ferns',
  'ferry', 'fever', 'fiber', 'field', 'fiery', 'fifth', 'fifty', 'fight', 'filed', 'filer',
  'files', 'fills', 'films', 'filth', 'final', 'finch', 'finds', 'fined', 'finer', 'fines',
  'fired', 'fires', 'first', 'fixed', 'fixer', 'fixes', 'fizzy', 'flag',
  'flake', 'flame', 'flank', 'flare', 'flash', 'flask', 'flesh', 'flick', 'flier', 'flies',
  'fling', 'float', 'flock', 'flood', 'floor', 'flour', 'flown', 'flows', 'fluid', 'flunk',
  'flush', 'flute', 'foams', 'focal', 'focus', 'foggy', 'foils', 'folds', 'folks', 'folly',
  'fonts', 'foods', 'fools', 'force', 'forge', 'forgo', 'forms', 'forth', 'forty', 'forum',
  'fossil', 'foster', 'found', 'fours', 'fowls', 'frame', 'frank', 'fraud', 'freak', 'freed',
  'fresh', 'friar', 'fried', 'fries', 'fright', 'frisk', 'frock', 'frogs', 'front', 'frost',
  'froth', 'frown', 'froze', 'fruit', 'fully', 'fumes', 'funds', 'fungi', 'funky', 'funny',
  'furry', 'fused', 'fuses', 'gable', 'games', 'gamma', 'gangs', 'gates', 'gauge', 'gauze',
  'gavel', 'gawks', 'gazes', 'gears', 'geese', 'genre', 'genre', 'gents', 'genus', 'germs',
  'ghost', 'giant', 'gifts', 'gills', 'girls', 'given', 'giver', 'gives', 'gland', 'glare',
  'glass', 'glaze', 'gleam', 'glean', 'glide', 'glint', 'globe', 'gloom', 'glory', 'gloss',
  'glove', 'glued', 'glues', 'gnash', 'gnats', 'goals', 'goats', 'godly', 'going', 'golds',
  'golly', 'gonna', 'goods', 'gooey', 'goons', 'goose', 'gored', 'gorge', 'gorilla', 'gotta',
  'gouge', 'gowns', 'grace', 'grade', 'graft', 'grail', 'grain', 'grant', 'grape', 'graph',
  'grasp', 'grass', 'grate', 'grave', 'gravy', 'graze', 'great', 'greed', 'greek', 'green',
  'greet', 'grief', 'grill', 'grime', 'grind', 'grins', 'grips', 'grist', 'grits', 'groan',
  'groom', 'grope', 'gross', 'group', 'grout', 'grove', 'grows', 'gruel', 'gruff', 'grunt',
  'guard', 'guess', 'guest', 'guide', 'guild', 'guilt', 'guise', 'gulch', 'gulfs', 'gulls',
  'gulps', 'gummy', 'gurus', 'gusts', 'gutsy', 'habit', 'hacks', 'hails', 'hairs', 'hairy',
  'halts', 'hands', 'handy', 'hangs', 'hanky', 'happy', 'hardy', 'harem', 'harms', 'harps',
  'harsh', 'hasps', 'haste', 'hasty', 'hatch', 'hated', 'hater', 'hates', 'hauls', 'haunt',
  'haven', 'havoc', 'hawks', 'hazel', 'heads', 'heals', 'heaps', 'heard', 'hears', 'heart',
  'heats', 'heath', 'heats', 'heave', 'heavy', 'hedge', 'heeds', 'heels', 'hefty', 'heirs',
  'heist', 'hells', 'hello', 'helms', 'helps', 'hence', 'henry', 'herbs', 'herds', 'heron',
  'heros', 'hinge', 'hints', 'hippo', 'hired', 'hires', 'hitch', 'hives', 'hoary', 'hobby',
  'hoist', 'holds', 'holes', 'holly', 'homes', 'homey', 'honey', 'honor', 'hooks', 'hoops',
  'horns', 'horny', 'horse', 'hoses', 'hosts', 'hotly', 'hound', 'hours', 'house', 'hover',
  'howdy', 'howls', 'hubs', 'huffs', 'huffy', 'hugs', 'hulks', 'hulls', 'human', 'humid',
  'humor', 'humps', 'humus', 'hunch', 'hunks', 'hunts', 'hurls', 'hurry', 'hurts', 'husks',
  'hussy', 'husky', 'hydro', 'hymns', 'hyper', 'iambs', 'icier', 'icily', 'icons', 'ideal',
  'ideas', 'idiom', 'idiot', 'idles', 'idyll', 'igloo', 'image', 'imply', 'inane', 'incur',
  'index', 'india', 'infer', 'infix', 'infra', 'ingot', 'inked', 'inker', 'inlet', 'inner',
  'input', 'inter', 'intro', 'ionic', 'irate', 'irony', 'issue', 'itch',
  'items', 'ivory', 'jabot', 'jacks', 'jacky', 'jades', 'jaggy', 'jails', 'james', 'jaunt',
  'jazzy', 'jeans', 'jeers', 'jelly', 'jenny', 'jesuit', 'jetty', 'jewel', 'jiffy', 'jingo',
  'jinns', 'jived', 'jiver', 'jives', 'joans', 'jocky', 'joins', 'joint', 'joist', 'joker',
  'jokes', 'jolly', 'jolts', 'joust', 'jowls', 'joyed', 'judge', 'juice', 'juicy', 'jumbo',
  'jumps', 'jumpy', 'junco', 'junks', 'junky', 'juror', 'jurat', 'jutty', 'kales', 'karma',
  'kayak', 'keels', 'keeps', 'kelps', 'ketch', 'ketyl', 'keys', 'khaki', 'kicks', 'kills',
  'kilns', 'kilos', 'kilts', 'kinds', 'kinky', 'kiosk', 'kirks', 'kisks', 'kites', 'kitty',
  'knack', 'knead', 'kneel', 'knelt', 'knife', 'knock', 'knoll', 'knots', 'knotty', 'know',
  'knows', 'knubs', 'knuck', 'label', 'labor', 'laced', 'lacer', 'laces', 'lacks', 'lacy',
  'lager', 'lairs', 'lakes', 'lamas', 'lambs', 'lamed', 'lames', 'lamps', 'lance', 'lands',
  'lanes', 'lanky', 'lapse', 'larch', 'lards', 'lares', 'lark', 'larks', 'larva', 'lasso',
  'lasts', 'latch', 'lated', 'later', 'lates', 'lathe', 'laths', 'latin', 'lauds', 'laugh',
  'laund', 'lava', 'lavas', 'lawns', 'lawny', 'laws', 'laxer', 'laxly', 'layer', 'layed',
  'lays', 'lazed', 'lazes', 'lazys', 'leach', 'leads', 'leady', 'leafs', 'leafy', 'league',
  'leaks', 'leaky', 'leans', 'leant', 'leaps', 'leapt', 'learn', 'lease', 'leash', 'leass',
  'least', 'leats', 'leave', 'ledge', 'ledgy', 'leeks', 'leers', 'leery', 'leets', 'lefts',
  'lefty', 'legal', 'leges', 'leggy', 'legin', 'legion', 'lemma', 'lemon', 'lemur', 'lends',
  'lenes', 'lenis', 'leno', 'lenos', 'lens', 'lent', 'lento', 'leone', 'leper', 'lepra',
  'leshy', 'less', 'lesse', 'lesses', 'lessing', 'lest', 'let', 'lethal', 'letch', 'lethe',
  'lethes', 'lets', 'lette', 'letter', 'letup', 'levee', 'level', 'lever', 'leven', 'levin',
  'levity', 'levy', 'lewd', 'lewis', 'lexis', 'liar', 'liars', 'libel', 'libra', 'lice',
  'lichen', 'licit', 'lick', 'licked', 'licker', 'licks', 'lid', 'lids', 'lied', 'lief',
  'liege', 'lien', 'liens', 'lies', 'lieu', 'life', 'lifts', 'light', 'lights', 'lignin',
  'lignum', 'likable', 'like', 'liked', 'liken', 'likes', 'lilac', 'lilies', 'lilted', 'lilts',
  'lily', 'lima', 'limb', 'limbate', 'limbed', 'limber', 'limbo', 'limbos', 'limbs', 'lime',
  'limed', 'limen', 'limey', 'limit', 'limits', 'limmer', 'limn', 'limned', 'limns', 'limo',
  'limps', 'limpy', 'limy', 'line', 'lined', 'linen', 'linens', 'liner', 'liners', 'lines',
  'linga', 'linger', 'lingo', 'lingua', 'linguae', 'lingue', 'lingy', 'linhay', 'linier',
  'lining', 'linings', 'link', 'linkage', 'linked', 'linker', 'links', 'linky', 'linny',
  'lino', 'linoleums', 'linotype', 'lins', 'linseed', 'linter', 'lintier', 'linty', 'linum',
  'lion', 'lioness', 'lionly', 'lions', 'lipase', 'lipid', 'lipids', 'lipins', 'lipoid',
  'lipoma', 'lipomas', 'lipped', 'lippy', 'lipread', 'lips', 'lira', 'liras', 'lire', 'lirot',
  'lis', 'lisle', 'lisp', 'lisped', 'lisper', 'lisps', 'lissom', 'list', 'listed', 'listen',
  'lister', 'lists', 'lit', 'litai', 'litany', 'litas', 'latch', 'lite', 'liter', 'literal',
  'literate', 'liters', 'lites', 'lithaemia', 'litharge', 'lithe', 'lithely', 'lither',
  'lithesome', 'lithest', 'lithia', 'lithias', 'lithic', 'lithium', 'litigable', 'litigate',
  'litigious', 'litmus', 'litoral', 'litotes', 'litre', 'litres', 'lits', 'litter', 'litterer',
  'litterers', 'litterin', 'litterings', 'litters', 'littery', 'little', 'littleness', 'littler',
  'littlest', 'littling', 'littlings', 'litton', 'littoral', 'littorals', 'lituus', 'lituuses',
  'liturgic', 'liturgical', 'liturgically', 'liturgist', 'liturgists', 'liturgy', 'livable',
  'livableness', 'live', 'liveably', 'lived', 'livedo', 'livelied', 'livelier', 'liveliest',
  'livelily', 'liveliness', 'lively', 'liven', 'livened', 'livening', 'livens', 'livenness',
  'liven', 'livens', 'liver', 'livered', 'liveried', 'liveries', 'liverish', 'liverleaf',
  'liverleafs', 'liverly', 'liverness', 'livers', 'liverwort', 'liverworts', 'livery',
  'liverymen', 'lives', 'livest', 'livid', 'lividly', 'lividness', 'living', 'livingly',
  'livingness', 'livings', 'livious', 'livonias', 'livonians', 'livraison', 'livre', 'livres',
  'lividly', 'lizard', 'lizards'
]

export function getRandomWordleWord() {
  return WORDLE_WORDS[Math.floor(Math.random() * WORDLE_WORDS.length)]
}
